- common/src/main/res/values-en/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values/strings.xml
Updated outdated string resource xmls.
> Updated translation files

- common/src/main/res/values-en/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values/strings.xml
> string update

- common/src/main/res/values-fr/strings.xml
> update french strings

- README.md
Add missing hyperlinks to the README.
> Add missing hyperlinks

- eval/src/androidTest/java/ch/admin/bag/covidcertificate/eval/TestDataGenerator.kt
- eval/src/androidTest/java/ch/admin/bag/covidcertificate/eval/nationalrules/NationalRulesVerifierTest.kt
- eval/src/main/java/ch/admin/bag/covidcertificate/eval/utils/VaccinationEntryUtils.kt
Add new tests for checking the valid Until date. And set the clock for the vaccine cert to a start of day
> add new tests, and set clock to at start of day for vaccines

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainActivity.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/data/SecureStorage.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/networking/ConfigRepository.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/SecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/networking/ConfigRepository.kt
make sure that the config request is executed at every app start directly after an app or OS update
> Config Request Bugfix

- eval/src/androidTest/java/ch/admin/bag/covidcertificate/eval/chain/VerificationCoseServiceTest.kt
- eval/src/main/java/ch/admin/bag/covidcertificate/eval/Eval.kt
- eval/src/main/java/ch/admin/bag/covidcertificate/eval/chain/DecompressionService.kt
> Limit size of decompressed byte array

- common/src/main/res/values-en/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values/strings.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailItemListBuilder.kt
Change naming, order and styling of test result in detail screen
> Test Result Naming

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QrScanFragment.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/verification/CertificateVerifier.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/qr/VerifierQrScanFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/add/CertificateAddFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailItemListBuilder.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatesPagerAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/PagerDiffUtil.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListViewHolder.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/VerifiedCeritificateItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/qr/WalletQrScanFragment.kt
This PR contains the edits in the app going hand in hand with the SDK refactoring [here](https://github.com/admin-ch/CovidCertificate-SDK-Android/pull/4).
> Adapt to decode flow change in SDK

- README.md
Add badges linking to Google Play.
Preview it here: https://github.com/admin-ch/CovidCertificate-App-Android/tree/feature/play-badge
> Add Google Play badges

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QRCodeReaderHelper.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/PdfViewModel.kt
Simplify the levels of nesting in the importPdf function, check all pdf pages for QR codes, go with the first found.
> Make importPdf more readable

- wallet/src/main/res/layout/fragment_home.xml
> set correct titel

- common/src/main/java/ch/admin/bag/covidcertificate/common/util/VerificationStateUtil.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/util/VerificationStateUtil.kt
SDK PR: https://github.com/admin-ch/CovidCertificate-SDK-Android/pull/26
> Fixed revoked certificate error

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatesPagerAdapter.kt
Handle same euDGC content. Change to qrdata for pager to handle
> Handle same euDGC content. Change to qrdata for pager to handle

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/logic/Luhn.kt
- wallet/src/test/java/ch/admin/bag/covidcertificate/wallet/transfercode/LuhnTest.kt
- wallet/src/test/java/ch/admin/bag/covidcertificate/wallet/transfercode/LuhnTestWrongCodes.kt
Handle wrong alphabets chars better and test that some wrong codes are detected as wrong.
> Add luhn tests that should fail

- common/src/main/java/ch/admin/bag/covidcertificate/common/data/ConfigSecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/CertificateStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletSecureStorage.kt
Update SDK and change encrypted shared preferences initialization
> Encryption Update

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
Disable on back pressed dispatcher on pop backstack
> Fix on back pressed crash

- wallet/src/main/AndroidManifest.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/DeeplinkViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
Upcoming versions of SwissCovid [support](https://github.com/SwissCovid/swisscovid-app-android/blob/develop/app/src/main/java/ch/admin/bag/dp3t/checkin/checkinflow/QrCodeScannerFragment.kt) scanning a COVID Certificate QR code and will then deeplink to this app.
> Add deeplink

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/PdfViewModel.kt
- wallet/src/main/res/drawable/bg_add_certificate_option.xml
- wallet/src/main/res/layout/fragment_home.xml
- wallet/src/main/res/layout/partial_home_add_certificate_options.xml
> PDF Import

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationStateUtil.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/debug/DebugCertificateItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/debug/DebugCertificatesListAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/debug/DebugCertificatesListViewHolder.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/debug/DebugFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatesPagerAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/PagerDiffUtil.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/WalletItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/res/layout/item_debug_certificate_list.xml
Properly handle the case, when (e.g. by transfer) an invalid and undecodeable certificate has been added to the wallet.
> Wallet - Undecodeable Certificate

- wallet/src/main/res/drawable/bg_add_certificate_option.xml
- wallet/src/main/res/drawable/ic_pdf.xml
- wallet/src/main/res/drawable/ic_qrcode_scan.xml
- wallet/src/main/res/layout/partial_home_add_certificate_options.xml
Add the new UI for importing PDFs more easily.
> New import button UI

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletDataSecureStorage.kt
Before adding a certificate, check if it is already available in storage.
> Don't add same certificate twice

- wallet/src/main/res/layout/fragment_transfer_code_creation.xml
Update padding on transfer code creation screen
> Transfer Code Padding

- wallet/src/main/res/layout/fragment_transfer_code_intro.xml
> Fix how to button offset

- common/src/main/res/values/colors.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/res/drawable/bg_bubble_bottom_left.xml
- wallet/src/main/res/layout/fragment_home.xml
- wallet/src/main/res/layout/partial_home_add_certificate_options.xml
Make homescreen layout scrollable with a larger area if the screen size is too small
> Improve homescreen layout on small devices

- wallet/src/main/AndroidManifest.xml
> Fix to portrait for wallet onboarding

- common/src/main/java/ch/admin/bag/covidcertificate/common/faq/FaqAdapter.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/faq/FaqFragment.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/faq/FaqItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeHowToFragment.kt
ClickListener was not passed into the FAQ-Adapter. Refactored to a lambda.
> Added onUrlClickListener for Transfer FAQs

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/res/layout/fragment_certificate_detail.xml
- wallet/src/main/res/layout/item_detail_title.xml
- wallet/src/main/res/layout/item_detail_value.xml
- wallet/src/main/res/layout/item_detail_value_without_label.xml
Update item padding in certificate details list
> Certificate Details Padding

- common/src/main/assets/impressum/de/impressum.html
- common/src/main/assets/impressum/en/impressum.html
- common/src/main/assets/impressum/fr/impressum.html
- common/src/main/assets/impressum/it/impressum.html
- common/src/main/assets/impressum/rm/impressum.html
- common/src/main/java/ch/admin/bag/covidcertificate/common/html/BuildInfo.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/util/AssetUtil.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
Send different app identifier as get parameter in imprint developer link
> Imprint Link App Identifier

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/HomeFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/pager/HomescreenPagerFragment.kt
- verifier/src/main/res/layout/fragment_home_screen_pager.xml
Fix long description text in verifier pager cut off and misaligned
> Verifier Description Text

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QrScanFragment.kt
Fix image analyzer removed prematurely when QR code was detected but not decoded successfully
> Fix scanning invalid QR code

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/view/TransferCodeBubbleView.kt
Remove check for state equality because transfer code might have been updated but state didnt change
> Transfer Code View Update

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QrScanFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/qr/VerifierQrScanFragment.kt
- verifier/src/main/res/layout/fragment_qr_scan.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatesPagerAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/PagerDiffUtil.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/WalletItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListViewHolder.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/qr/WalletQrScanFragment.kt
- wallet/src/main/res/layout/fragment_certificate_light_detail.xml
- wallet/src/main/res/layout/fragment_certificate_light_pager.xml
Implement certificate light handling in homescreen pager, list and wallet scanner
> Certificate Light Pager & List

- common/src/main/java/ch/admin/bag/covidcertificate/common/config/ConfigModel.kt
- wallet/src/main/AndroidManifest.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletDataSecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/net/CertificateLightRepository.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/net/CertificateLightService.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/PdfViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/export/PdfExportFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/export/PdfExportState.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/net/PdfExportRepository.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/net/PdfExportRequestBody.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/net/PdfExportResponse.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/net/PdfExportService.kt
- wallet/src/main/res/layout/fragment_certificate_detail.xml
- wallet/src/main/res/layout/fragment_pdf_export.xml
- wallet/src/main/res/xml/filepaths.xml
Implement the export and sharing of a certificate to a PDF
> Certificate PDF Export

- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationStateUtil.kt
Show correct strings for certificate light success and expired in verifier
> Certificate Light Verifier

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletDataSecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightViewModel.kt
Automatically delete certificate light on expiration and show original certificate in its stead
> Certificate Light Deactivation/Expiration

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/HomeFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
Prevent any network calls to be made before accepting the terms and conditions
> Verifier Networking

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/net/CertificateLightResponse.kt
Change naming of certificate light qr code response parameter and update SDK
> Certificate Light Endpoint Parameter

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
Set correct status icon for certificate light based on verification state
> Certificate Light Status Icon

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/add/CertificateAddFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
Fix date of birth parsing by formatting in SDK or returning original value
> Date of Birth Parsing

- verifier/src/main/play/release-notes/en-US/default.txt
- wallet/src/main/play/release-notes/en-US/default.txt
This time the right way around, last time verifier and wallet were swapped...
> Add release notes for F-Droid

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
Set certificate light and pdf export button enabled state based on certificate issuer and verification state
> Certificate Transformation Buttons

- common/build.gradle
- common/src/main/java/ch/admin/bag/covidcertificate/common/util/EnvironmentUtil.kt
- verifier/build.gradle
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainApplication.kt
- wallet/build.gradle
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainApplication.kt
Initialize SDK with environment and increase app version to 2.2.0 / 2200
> SDK-Android Environment

- .github/workflows/appcenter_verifier_abn.yml
- .github/workflows/appcenter_verifier_dev.yml
- .github/workflows/appcenter_verifier_prod.yml
- .github/workflows/appcenter_wallet_abn.yml
- .github/workflows/appcenter_wallet_dev.yml
- .github/workflows/appcenter_wallet_prod.yml
Mitigate supply chain attacks by fixing sha-hash of external action.
> fix github action to sha-hash of v1.3.2

- common/build.gradle
- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
CovidCertificate-App Version 2.2.0
> Version 2.2.0

- wallet/src/main/res/layout/fragment_certificate_light_detail.xml
TextFrame was not fully expanded. Changed constraint
> show document text for qr code light

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/view/TransferCodeView.kt
- wallet/src/main/res/layout/view_transfer_code.xml
Add click to copy functionality for transfer code view
> Transfer Code Click to Copy

- common/build.gradle
- gradle.properties
Update bouncy castle from 1.65 to 1.69
> Bouncy Castle Update

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/export/PdfExportShareContract.kt
> PDF File Deletion

- verifier/build.gradle
- wallet/build.gradle
- wallet/src/main/res/layout/fragment_certificate_light_pager.xml
- wallet/src/main/res/layout/fragment_certificate_pager.xml
- wallet/src/main/res/layout/fragment_transfer_code_pager.xml
Update certificate pager title margins and set auto text size
> Certificate Pager Title

- common/src/main/java/ch/admin/bag/covidcertificate/common/dialog/InfoDialogFragment.kt
Use correct field for info dialog text
> Info Dialog Text

- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightConversionFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/model/CertificateLightConversionResponse.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/model/CertificateLightConversionState.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/net/CertificateLightRepository.kt
Display specific error message when certificate light conversion rate limit is reached
> Certificate Light Rate Limit

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QRCodeReaderHelper.kt
To avoid OOM errors on older devices.
Possibly resolves https://github.com/admin-ch/CovidCertificate-App-Android/issues/237.
> reduce memory usage during PDF import

- Dockerfile
- build.gradle
- common/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- verifier/build.gradle
- wallet/build.gradle
Also updated to Gradle & AGP v7.0
UbDiag plugin ref: https://github.com/UbiqueInnovation/gradle-plugin-ubdiag-android
> Launcher icon flavor label

- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailAdapter.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailItemListBuilder.kt
- wallet/src/main/res/layout/item_detail_value.xml
Copy UVCI to clipboard when clicking on it
> UVCI Copy on Click

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
Pop verifier backstack only to scanner when put into background with details open
> Verifier Details Backstack

- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeCreationViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/model/TransferCodeCreationResponse.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/net/DeliveryRepository.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/view/TransferCodeBubbleView.kt
- wallet/src/main/res/layout/view_transfer_code_bubble.xml
Display special error when device time deviates from server time
> Transfer Code Time Error Handling

- wallet/src/main/res/layout/fragment_transfer_code_detail.xml
Fix transfer code detail layout issue
> Transfer Code Detail Layout

- common/src/main/java/ch/admin/bag/covidcertificate/common/util/HttpIOException.kt
- wallet/src/dev/java/ch/admin/bag/covidcertificate/wallet/debug/DebugCertificateItem.kt
- wallet/src/dev/java/ch/admin/bag/covidcertificate/wallet/debug/WalletDebugFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/StatefulWalletItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/net/DeliveryRepository.kt
Try transfer code conversion as well in wallet list
> Wallet List Transfer Code Conversion

- verifier/src/main/AndroidManifest.xml
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainApplication.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/extensions/ContextExtensions.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/qr/VerifierQrScanFragment.kt
Add zebra phone config setup and intent handling
> Zebra Phone Intent Handling

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QrScanFragment.kt
- common/src/main/res/drawable/ic_camera_switch.xml
- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainApplication.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/data/VerifierSecureStorage.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/qr/VerifierQrScanFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/zebra/ZebraDataWedgeApiUtil.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/zebra/ZebraResultActionBroadcastReceiver.kt
- verifier/src/main/res/layout/fragment_qr_scan.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/qr/WalletQrScanFragment.kt
- wallet/src/main/res/layout/fragment_qr_scan.xml
Implement zebra phone detection and camera activate/deactivate
> External Hardware Scanner Detection

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/TransferCodePagerFragment.kt
Check if available space is enough to show both the vaccination hint and waiting image
> Vaccination Hint Space

- common/src/main/java/ch/admin/bag/covidcertificate/common/exception/HttpIOException.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/exception/TimeDeviationException.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/TransferCodePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeCreationViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/net/DeliveryRepository.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/view/TransferCodeBubbleView.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/worker/TransferWorker.kt
Add time deviation handling in transfer code pager, detail and list
> Transfer Code Time Deviation Handling

- build.gradle
- common/build.gradle
- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QrScanFragment.kt
- verifier/build.gradle
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/HomeFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/qr/VerifierQrScanFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/zebra/ZebraActionBroadcastReceiver.kt
- wallet/build.gradle
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/TransferCodePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
Version 2.6.1 Release:
* Zebra intent handling improvements
* Various bugfixes
> Version 2.6.1

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainApplication.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletDataSecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/data/WalletSecureStorage.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeCreationViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/model/TransferCodeModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/worker/TransferWorker.kt
Add read-write lock to wallet data and add check before deleting transfer code on server
> Transfer Code KPG Error

- .github/workflows/appcenter_verifier_prodfdroid.yml
- .github/workflows/appcenter_wallet_prodfdroid.yml
These are copied from the prod workflows with the commands and paths adjusted.
> Add workflows for prodfdroid

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesAndConfigViewModel.kt
Always show error when force refreshing
> Force Refresh Behavior

- .github/workflows/gradle-wrapper-validation.yml
Same as https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/pull/54.
> Update Github Workflow dependencies

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QRCodeReaderHelper.kt
Check for low memory before rendering large bitmap and use multiple binarizers to improve pdf import accuracy
> PDF Import Improvements

- loadConfigs.sh
Create script to automate the loading of the fallback config files
> Fallback Config Load Script

- .github/actions/gradle_docker/main.sh
- Dockerfile
- buildAndCompare.sh
The commit messages pretty much explain it.
> Use gradle wrapper for build

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/res/layout/fragment_certificate_add.xml
- wallet/src/main/res/layout/item_detail_modes_list.xml
Fix some small UI bugs (topmost dashed line missing or having bad padding, inconsistent error icons).
> Minor UI bugs
