admin-ch/CovidCertificate-App-Android

- common/src/main/java/ch/admin/bag/covidcertificate/common/util/UiUtil.kt
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
The dialogs currently don't contain much sensitive information ("You should update the app." "Do you really want to delete?"), but we should still aim for completeness.
> Block screenshots of dialogs too

- common/src/main/assets/impressum/de/licence.html
- common/src/main/assets/impressum/en/licence.html
- common/src/main/assets/impressum/fr/licence.html
- common/src/main/assets/impressum/it/licence.html
I might be totally wrong but referring to the BSD-3-Clause and MIT licence on the original page would be better, although the linked to one is identical, of course.
> BSD-3-Clause and MIT licence URL

- common/src/main/java/ch/admin/bag/covidcertificate/common/net/ConfigRepository.kt
The main changes are in https://github.com/admin-ch/CovidCertificate-SDK-Android/pull/19.
Since this depends on the latest SDK commit, the submodule will pull in the whole API Key shebang as well. So I guess we keep this a draft until we've decided how we'll to that?
> Update SDK to CN pinning

- verifier/build.gradle
- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/MainApplication.kt
- wallet/build.gradle
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainApplication.kt
To better represent what it does.
See the SDK PR here: https://github.com/admin-ch/CovidCertificate-SDK-Android/pull/22
> Rename api key to app token

- common/src/main/java/ch/admin/bag/covidcertificate/common/html/HtmlFragment.kt
It's a leftover that is not needed. All HTML that we load is from the assets, and there is no JS anywhere.
Tested by clicking all the links in the imprint, all work as before and as expected.
> Disable javascript in HtmlFragment

- .github/workflows/appcenter_verifier_abn.yml
- .github/workflows/appcenter_verifier_dev.yml
- .github/workflows/appcenter_verifier_prod.yml
- .github/workflows/appcenter_wallet_abn.yml
- .github/workflows/appcenter_wallet_dev.yml
- .github/workflows/appcenter_wallet_prod.yml
- .github/workflows/gradle-wrapper-validation.yml
Motivated by #79 to prevent commits introducing bad gradle jars.
See https://github.com/marketplace/actions/gradle-wrapper-validation.
Also unifies workflow naming.
> Add gradle wrapper validation

- common/src/main/java/ch/admin/bag/covidcertificate/common/net/ConfigRepository.kt
- wallet/build.gradle
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainApplication.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/worker/TransferWorker.kt
Added a periodic worker to regularly query for available certificates, if the wallet contains any transfer codes. The worker is started when hiding the app and cancelled on app start.
> Added transfer worker for periodic certificate pulling in the background

- common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QRCodeReaderHelper.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/add/CertificateAddFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/PdfViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/qr/WalletQrScanFragment.kt
Attempt to fix the issues with PDF import on some devices with the new, more dense PDFs. Just try harder ;)
While I'm at it, also hide the "Scan again" button when the CertificateAddFragment was opened via a deeplink or PDF import.
> Fix pdf import on some devices

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/view/TransferCodeBubbleView.kt
- wallet/src/main/res/layout/view_transfer_code_waiting.xml
Fix initial state of ripple in transfer illu and the transfer detail error indicator is now correctly removed after successful retry
> Transfer Certificate Detail Error Indicator

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/CertificatesViewModel.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/TransferCodePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeViewModel.kt
* Call complete endpoint on transfer code delete
* Remove certificate download in wallet data observeForever because it's an unnecessary additional call. The request is anyway done in the onViewCreated call of the pager fragment
> Transfer Code Complete

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/MainActivity.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- Moving the `CovidCertificateSdk.registerWithLifecycle` to `showHomeFragment` to easily cover both paths there (onboarding activity finished or was already completed days ago).
- Moving the trustlist refresh and config loading to the HomeFragment, since that is one-shot and even though the fragment's lifecycleScope is different from the activity's, this should still be enough.
> Fix networking only once onboarding is completed

- common/src/main/java/ch/admin/bag/covidcertificate/common/util/ErrorHelper.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
This should not really happen ever, so don't bother with translations. Still, better to show an English toast than crashing the app.
> Catch potential ActivityNotFoundExceptions

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
Remove bitmap filtering for certificate light QR codes because they are big enough and aren't scaled up
> Certificate Light Bitmap Filtering

- wallet/src/main/AndroidManifest.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/export/PdfExportFragment.kt
Make fileprovider authority dependent on the application id instead of hardcoding the package name
> Fix fileprovider authority

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/transfercode/TransferCodeCreationFragment.kt
This avoids the user missing an already-received transfer.
Set a small delay to not be confusing if the user switches apps for only a second.
> Auto-close TransferCodeCreationFragment when returning after success

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/export/PdfExportShareContract.kt
Use Android's [share sheet](https://developer.android.com/training/sharing/send#why-to-use-system-sharesheet) for exporting the PDF. Using ACTION_CHOOSER also matches nicely with what [it's intended for](https://developer.android.com/reference/android/content/Intent#ACTION_CHOOSER).
Pro:
- You always get a chooser. If you click "Always" in the old version, you're in trouble.
- You get more/better suggestions for contacts/apps
- It looks nicer because Android opens it only to 2/3 of the screensize
Con:
- Slightly worse usage of space (more entries, 10 vs 12, but less apps)
- Android doesn't preview PDFs :(
| Before | After |
| --- | --- |
|  <img src=https://user-images.githubusercontent.com/56064810/130361907-a740fe74-6240-4af5-a66a-41ca0add5506.png width=300px> |  <img …
> Show nice chooser to share PDF

- common/src/main/java/ch/admin/bag/covidcertificate/common/extensions/WindowExtensions.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
Increase screen brightness on certificate light details same as for normal certificates.
This fixes https://github.com/admin-ch/CovidCertificate-App-Android/issues/259
> Certificate Light Screen Brightness

- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/HomeFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/pdf/PdfViewModel.kt
Previously if the PDF import failed the error text said "Invalid format". This confused a few people who were trying to import correct PDFs, but for which ZXing failed to find the QR code.
This PR improves the error message to give a better - albeit somewhat generic - reason ("either wrong QR code or QR code could not be found").
> Improve PDF import error message

- common/build.gradle
- common/src/main/java/ch/admin/bag/covidcertificate/common/util/EnvironmentUtil.kt
- common/src/prodfdroid/java/ch/admin/bag/covidcertificate/common/debug/DebugFragment.kt
- verifier/build.gradle
- wallet/build.gradle
- wallet/src/prodfdroid/java/ch/admin/bag/covidcertificate/wallet/debug/WalletDebugFragment.kt
This copies everything from prod, but raises the minSdkVersion to 24.
See https://github.com/admin-ch/CovidCertificate-App-Android/issues/304.
Build it with `./gradlew wallet:assembleProdfdroidRelease`.
> Add prodfdroid build flavour

- REPRODUCIBLE_BUILDS.md
- buildAndCompare.sh
This PR improves the reproducible build documentation and script, building upon #287.
Features:
- Option to autogenerate a keystore with dummy credentials.
This is useful for users, while we retain the possibility to pass a keystore to be used for signing.
- Option to build the fdroid flavour introduced in #314.
- Simplify the REPRODUCIBLE_BUILDS.md by not having 2 sections for both the wallet and the verifier, and by referencing the buildAndCompare.sh script (rather than providing all commands that the user should run).
- Improve the script to be on shorter lines (especially the `docker run` command)
- Prompt the user to pass a `buildBranch` that overrides whatever is checked out. This is needed for reproducing from git tags. Without this, the gradle variable `branch` (which is set by …
> Improve build scripts

- verifier/src/main/java/ch/admin/bag/covidcertificate/verifier/verification/VerificationFragment.kt
- wallet/src/dev/java/ch/admin/bag/covidcertificate/wallet/debug/DebugCertificateItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/add/CertificateAddFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/light/CertificateLightPagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
~*Marked as WIP until https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/pull/60 is propagated up here (this is why the CI build fails). Otherwise ready!*~
Use the helper methods introduced in the SDK [here](https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/pull/60) to print the names. Fixes #370.
What is fixed:
- wallet: did not handle the non-standard names being null, now handled.
- verifier: non-standard names =null were already handled, now standardizedGivenName=null is handled as well.
Tested with some Swiss certificates (nothing breaks) and the topmost certificate from Singapore [here](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/SG) (it's actually a fix).
|Before|After|
|---|---|
| <img …
> Use 'null-safe' helpers to print the PersonName. Fixes #370.

- common/src/main/java/ch/admin/bag/covidcertificate/common/config/ConfigModel.kt
- common/src/main/java/ch/admin/bag/covidcertificate/common/extensions/DccCertExtensions.kt
- common/src/main/res/values-de/strings.xml
- common/src/main/res/values-fr/strings.xml
- common/src/main/res/values-it/strings.xml
- common/src/main/res/values-rm/strings.xml
- common/src/main/res/values/strings.xml
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/detail/CertificateDetailFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/homescreen/pager/CertificatePagerFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/CertificatesListFragment.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/list/WalletDataListItem.kt
- wallet/src/main/java/ch/admin/bag/covidcertificate/wallet/util/VerificationStateUtil.kt
- wallet/src/main/res/layout/fragment_certificate_detail.xml
Add feature flag to either show the "validity until" of certificates (including making them grey when they expire in Switzerland, as before), or showing the "valid since" of certificates (keeping them blue, new).
This is to avoid confusion between the validity in Switzerland and the validity for international travel.
Translations are missing.
> Cert display: validity until / validity since
